services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - ./mariadb:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      interval: 30s
      retries: 3
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MARIADB_ROOT_PASSWORD}"]
      timeout: 30s

  libService:
    build: ./MLib   # build from the project directory Dockerfile
    image: dz2-libservice
    ports:    # both services are in the same network by default; no additional port connections needed
      - "8080:8080"
    environment:
      TESTVAR: TESTVAL
    depends_on:
      - db  # start only after db is running
    command: bash -c "sleep 3 && exec /start_command.sh"  # wait a little for any small db initialization