services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - ./mariadb:/docker-entrypoint-initdb.d
      - ./MLib/data:/var/lib/mysql:Z  # setup volume for persistence when db is not running
    ports:
      - "3306:3306" # can be omited if we don't want visibility ouside docker env
    healthcheck:
      interval: 30s
      retries: 3
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      timeout: 30s

  libService:
    build: ./MLib   # build from the project directory Dockerfile
    image: dz2-libservice
    ports:
      - "8080:8080"
    environment:
      TESTVAR: TESTVAL
    depends_on:
      db:
        condition: service_healthy # start only after db is running and healthy
    command: bash -c "sleep 3 && exec /start_command.sh"  # wait a little for any small db initialization