services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_COFFEE_ROOT_PASSWORD}
    volumes:
      - ./mariadb:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      interval: 30s
      retries: 3
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      timeout: 30s
